name: project
description: "Blood Donation App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.1.10


  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  flex_color_picker: ^3.5.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  flutter_local_notifications: ^19.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #assets:
   # - assets/default_avatar.png
